name: 'Set up Please'
description: 'Set up Please in GitHub Actions'
author: 'sagikazarmark'
inputs:
  version:
    description: 'Please version. Overrides the version in .plzconfig.'
    default: ''
    required: false
  profile:
    description: 'Configuration profile name'
    default: ''
    required: false
  include:
    description: 'Label of targets to include in automatic detection'
    default: ''
    required: false
  exclude:
    description: 'Label of targets to exclude from automatic detection'
    default: ''
    required: false
  output:
    description: 'Output mode'
    default: 'plain'
    required: false
  verbosity:
    description: 'Verbosity of output'
    default: ''
    required: false
  save-logs:
    description: 'Save build logs as artifacts at the end of each job'
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: 'target'
  color: 'purple'
